name: Docker Image CI

# Start build on new push to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Use ubuntu to execute the actions
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Login to docker hub using previously set secrets
      - name: Log in to Docker Hub
        run:
          echo ${{ secrets.DOCKER_USERNAME }}


      # Extract commit info to tag the docker image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/cloudproject-ci-cd
          tags: |
            type=raw,value=c-{{sha}}
      # Push to your docker hub account
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
